### ISSUE TITLE
When editing a proposal from music, the interface changes the dept to museum studies

### ISSUE THREAD

**Issue by bnmnetp** [bnmnetp/apc_interface#1]
I suspect it is because MUS is a prefix of MUST and MUST is showing up first.  But we need to be a bit more diligent in populating this field of the editing page.

**Comment by jackjo06** [comment]
In proposal.js, the default department is set with the line 
`$scope.selectedDept = $filter("filter")($scope.depts, { abbrev : $scope.proposal.newCourse.dept})[0];`
which by default searches any string that matches "MUS" at the start. We can force the comparator to be more strict and only retrieve the items which match the department abbreviation exactly by changing this to
`$scope.selectedDept = $filter("filter")($scope.depts, { abbrev : $scope.proposal.newCourse.dept}, true)[0];`
After applying this fix, the error appears to have been fixed.

Documentation about the AngularJS filter can be found [here](https://docs.angularjs.org/api/ng/filter/filter).
